apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp1-deployment
  labels:
    app: java-webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-webapp1
  template:
    metadata:
      labels:
        app: java-webapp1
    spec:
      containers:
        - name: java-webapp1
          image: khravi/java-webapp:v3
          ports: 
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-webapp1-loadbalancer-service
  labels:
    app: java-webapp1
spec:
  type: LoadBalancer
  selector:
    app: java-webapp1
  ports:
    - port: 8080
      targetPort: 8080
