name: This workflow deploy the image to AKS QA env
on:
 workflow_dispatch:
 push:
   branches:
     - release/**
     - master
jobs:
  use_build:
    uses: ./.github/workflows/CI-java-build-package-maven.yml
    secrets: inherit
  deploy-qa:
    runs-on: ubuntu-latest
    environment: qa
    needs: [ use_build ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

    
